CREATE TABLE order_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(255) NOT NULL,
    event_time TIMESTAMP NOT NULL,
    gross_amount DECIMAL(15, 2) NOT NULL,
    discount DECIMAL(15, 2) DEFAULT 0,
    net_amount DECIMAL(15, 2) NOT NULL,
    partner_id VARCHAR(10) NOT NULL,
    sequence_number BIGINT NOT NULL,
    received_time TIMESTAMP NOT NULL,
    stream_offset BIGINT DEFAULT 0,
    processed_time TIMESTAMP NOT NULL,
    CONSTRAINT uq_partner_sequence UNIQUE (partner_id, sequence_number)
);
--TODO: add indexes for frequently queried fields

-- to handle trash responses from partners
CREATE TABLE error_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id VARCHAR(10),
    received_time TIMESTAMP NOT NULL,
    raw_payload TEXT,
    error_reasons TEXT
);